export const ITEMS = [
    {
        id: 0,
        name: 'Helmet',
        image: '/assets/images/helmet.jpg',
        category: 'safety',
        label: 'ultra safe',
        price: '4.99',
        featured: true,
        description: 'Un casco de seguridad útil para proteger en ámbitos como la construcción, fabricas y otros',
    },
    {
        id: 1,
        name: 'Audio protector',
        image: '/assets/images/audio.jpg',
        category: 'safety',
        label: 'noise filter',
        price: '12.99',
        featured: false,
        description: 'Protege de ruidos auditivos por encima de los decibeles considerados aceptables',
    },
    {
        id: 2,
        name: 'Glasses',
        image: '/assets/images/glasses.jpg',
        category: 'safety',
        label: 'New technology',
        price: '31.99',
        featured: false,
        description: 'Permite filtrar rayos ultravioleta, material anti rayas, anti caidas',
    },
    {
        id: 3,
        name: 'Gloves',
        image: '/assets/images/gloves.jpg',
        category: 'safety',
        label: '',
        price: '12.99',
        featured: false,
        description: 'Hechos de algodón con goma antideslizante, especial para industria química.',
    }
];
